### ISSUE TITLE
Players controlling Other players.

### ISSUE THREAD

**Issue by Matthewsworld** [sackboydj167/clash-of-forces-bug-tracker#1]
Well i just controlled my friend! When you control yourself, the other players around you follow your actions, this leads to glitching players, and that is... basically it.

**Comment by sackboydj167** [comment]
Ok, fixed in 0.8.2. The issue was that the movement script didn't check that the keypresses were coming from the local player and this would cause other players the move, only to teleport back when the network synced. Thanks for reporting this, you will be given 100G in-game.

**Comment by sackboydj167** [comment]
Fixed in 0.9.0.
